require "bundler/gem_tasks"

require 'rake/testtask'
Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/test*.rb']
  t.verbose = true
end

## The above includes all test files in a test directory
## It also sets the right load path for tests.

# require "./test/test_fasta_parser"
# task :default => [:commands]

# task :manage do
#   myTest = Unit_Test.new
#   myTest.test
# end
